# Generated by Django 5.2.7 on 2025-10-13 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HakiRecordApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='incident_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='statement',
            name='incident_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='incident_location',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='incident_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='incident_type',
            field=models.CharField(choices=[('theft', 'Theft'), ('murder', 'Murder'), ('child abuse', 'Child Abuse'), ('accident', 'Accident')], default='theft', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='suspect_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
